### ISSUE TITLE
App is not loading account data (error status code 403) 

### ISSUE THREAD

**Issue by Moonchildish** [AniLibApp/AniLib#109] opened 2024-11-10 12:47 UTC
## Device Information

- **Device:** Oneplus Nord
- **Android Version:** 11
- **App Version:** 2.0.1-43

## Description

App will not load any account information and does not show any anime manga on all tabs. 
It just says :  'something went wrong. Http request failed with status code 403'. 
I can go to the settings page, but besides that nothing shows up. 

## Screenshots (if applicable)

![Screenshot_20241110-134035](https://github.com/user-attachments/assets/43f637b7-fe09-426c-b175-c0c90e80bd13)
![Screenshot_20241110-134559](https://github.com/user-attachments/assets/8ae7911d-9b19-4184-8e46-0f7e0340204d)
![Screenshot_20241110-134612](https://github.com/user-attachments/assets/a3bc3733-e622-41b2-9f30-921aca2cdeb0)

## Additional Context

It was like this before I updated the app.

**Comment by rev0lgenX** [comment] 2024-11-10 13:37
The AniList API gives response message as "The AniList API has been temporarily disabled due to severe stability issues. Please check the official AniList Discord for more information."

So all I can do is wait. So please check out their discord server or message here if the issue is something else. 😭😭

**Comment by rev0lgenX** [comment] 2024-11-11 04:31
It's starting to work now. So closing the issue for now. I'll open it again if it stops to work.

**Closed** 2024-11-17 14:28 UTC
Labels: bug
